# Generated by Django 5.0.6 on 2024-06-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_department2_userinfo_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
