# Generated by Django 5.0.6 on 2024-06-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_department_department2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department2',
        ),
    ]
