# Generated by Django 5.0.6 on 2024-06-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_delete_department2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size2',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
