# Generated by Django 5.0.6 on 2024-06-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_userinfo_size2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size3',
            field=models.CharField(default=15, max_length=16),
            preserve_default=False,
        ),
    ]
