# Generated by Django 5.0.6 on 2024-06-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_userinfo_size3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size2',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size3',
        ),
    ]
